version: 3

vars:
  FINANCIAL_REPO: "https://github.com/ReLIFE-Project-EU/relife-financial-service.git"
  FORECASTING_REPO: "https://github.com/ReLIFE-Project-EU/relife-forecasting-service.git"
  TECHNICAL_REPO: "https://github.com/ReLIFE-Project-EU/relife-technical-service.git"

env: {}

dotenv:
  - .env.local
  - .env.default

tasks:
  default:
    silent: true
    cmds:
      - task --list

  debug-env:
    desc: "Display all environment variables that are currently set"
    silent: true
    cmds:
      - |
        grep -E '^[A-Z_]+=' {{.ROOT_DIR}}/.env.default | cut -d= -f1 | while read var; do
          if [ -n "${!var:-}" ]; then
            echo "${var}=${!var}"
          fi
        done

  up:
    desc: "Start all services in detached mode, rebuild images, and wait for health checks"
    cmds:
      - task: pull
      - |
        export APP_COMMIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
        export APP_COMMIT_DATE=$(git log -1 --format=%cI 2>/dev/null || echo "unknown")
        docker compose up -d --build --wait

  up-local:
    desc: "Start services using locally built API images from external-services"
    cmds:
      - |
        export APP_COMMIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
        export APP_COMMIT_DATE=$(git log -1 --format=%cI 2>/dev/null || echo "unknown")
        docker compose -f docker-compose.yml -f docker-compose.local.yml up -d --build --wait

  down:
    desc: "Stop and remove all running containers and networks"
    cmds:
      - docker compose down

  pull:
    desc: "Force pull the latest versions of all images defined in docker-compose.yml"
    cmds:
      - docker compose pull

  clean:
    prompt: "Are you sure you want to clean the services? This will remove all containers and volumes."
    desc: "Stop and remove all containers, networks, and volumes (destructive operation)"
    cmds:
      - docker compose down -v

  format-lint:
    desc: "Run Prettier and ESLint to auto-format and check code style and quality"
    cmds:
      - npm run format
      - npm run lint

  fetch-specs:
    desc: "Fetch OpenAPI specifications from running services and save them to api-specs directory"
    vars:
      TIMESTAMP:
        sh: date +%Y%m%d-%H%M%S
      FINANCIAL: financial
      FORECASTING: forecasting
      TECHNICAL: technical
    cmds:
      - mkdir -p {{.ROOT_DIR}}/api-specs/{{.TIMESTAMP}}
      - >
        docker compose exec -T {{.FINANCIAL}}
        curl -s -f http://localhost:9090/openapi.json > 
        {{.ROOT_DIR}}/api-specs/{{.TIMESTAMP}}/{{.FINANCIAL}}.json
      - >
        docker compose exec -T {{.FORECASTING}}
        curl -s -f http://localhost:9090/openapi.json > 
        {{.ROOT_DIR}}/api-specs/{{.TIMESTAMP}}/{{.FORECASTING}}.json
      - >
        docker compose exec -T {{.TECHNICAL}}
        curl -s -f http://localhost:9090/openapi.json > 
        {{.ROOT_DIR}}/api-specs/{{.TIMESTAMP}}/{{.TECHNICAL}}.json
      - echo "OpenAPI specs saved to {{.ROOT_DIR}}/api-specs/{{.TIMESTAMP}}"

  fetch-sources:
    desc: "Fetch source code for ReLIFE services (usage: task fetch-sources FINANCIAL_TREEISH=... FORECASTING_TREEISH=...)"
    vars:
      TARGET_DIR: "external-services"
      DEFAULT_TREEISH: '{{.TREEISH | default "main"}}'
    cmds:
      - |
        if [ -d "{{.TARGET_DIR}}/relife-financial-service" ] || \
           [ -d "{{.TARGET_DIR}}/relife-forecasting-service" ] || \
           [ -d "{{.TARGET_DIR}}/relife-technical-service" ]; then
          echo "fetch-sources aborted: target directories already exist. Remove them to re-clone."
          exit 1
        fi
      - >
        ./scripts/fetch-sources.sh
        "{{.FINANCIAL_REPO}}" 
        "{{.FINANCIAL_TREEISH | default .DEFAULT_TREEISH}}"
        "{{.TARGET_DIR}}/relife-financial-service"
      - >
        ./scripts/fetch-sources.sh
        "{{.FORECASTING_REPO}}" 
        "{{.FORECASTING_TREEISH | default .DEFAULT_TREEISH}}"
        "{{.TARGET_DIR}}/relife-forecasting-service"
      - >
        ./scripts/fetch-sources.sh
        "{{.TECHNICAL_REPO}}" 
        "{{.TECHNICAL_TREEISH | default .DEFAULT_TREEISH}}"
        "{{.TARGET_DIR}}/relife-technical-service"

  clean-sources:
    prompt: "Are you sure you want to delete the local service sources? This will remove those directories."
    desc: "Remove local clones of ReLIFE service sources"
    vars:
      TARGET_DIR: "external-services"
    cmds:
      - rm -rf "{{.TARGET_DIR}}/relife-financial-service"
      - rm -rf "{{.TARGET_DIR}}/relife-forecasting-service"
      - rm -rf "{{.TARGET_DIR}}/relife-technical-service"

  dev:
    desc: "Start the frontend development server and all backend services using Docker"
    cmds:
      - task: up
      - npm run dev

  dev-local:
    desc: "Start the frontend dev server with locally built API services"
    cmds:
      - task: up-local
      - npm run dev
